mod dtbstatic

diff --git a/.github/workflows/custom.yml b/.github/workflows/custom.yml
--- a/.github/workflows/custom.yml
+++ b/.github/workflows/custom.yml
@@ -824,11 +824,27 @@ jobs:
               echo "addons ==> [${item}]"
               if [ "dtbstatic" == "${item}" -a -n "${{ env.dtb }}" ]; then
                 echo "loacl dtbstatic ..."
-                cp -fv ${{ env.dtb }} ext/dtbstatic/releases/user_model.dtb
-                dtbhash="`sha256sum ext/dtbstatic/releases/user_model.dtb | awk -F' ' '{print$1}'`"
-                sed -i "s|@@@PATH@@@|${PWD}|g" ext/dtbstatic/rpext-index.json ext/dtbstatic/recipes/universal.json
-                sed -i "s|@@@HASH@@@|${dtbhash}|g" ext/dtbstatic/recipes/universal.json
-                ./ext-manager.sh add "file://localhost${PWD}/ext/dtbstatic/rpext-index.json"
+                EXT_PATH="`./ext/dtbstatic/make.sh "${{ env.dtb }}"`"
+                if [ -n "${EXT_PATH}" ]; then 
+                  echo "EXT_PATH: ${EXT_PATH}"
+                  ./ext-manager.sh add "${EXT_PATH}"
+                else
+                  echo "loacl dtbstatic error"
+                  exit 1
+                fi 
+              elif [ "localrss" == "${item}" ]; then
+                echo "loacl localrss ..."
+
+                paturl=$(cat config/${model}/${version}/config.json | jq -r '.os .pat_url')
+                patmd5=$(cat config/${model}/${version}/config.json | jq -r '.os .hash')
+                EXT_PATH="`./ext/localrss/make.sh "${paturl}" "${patmd5}"`"
+                if [ -n "${EXT_PATH}" ]; then 
+                  echo "EXT_PATH: ${EXT_PATH}"
+                  ./ext-manager.sh add "${EXT_PATH}"
+                else
+                  echo "loacl localrss error"
+                  exit 1
+                fi 
               else
                 ./ext-manager.sh add "${rpext}/addons/${item}/rpext-index.json"
               fi
