add kernelvers

diff --git a/.github/workflows/exts.yml b/.github/workflows/exts.yml
--- a/.github/workflows/exts.yml
+++ b/.github/workflows/exts.yml
@@ -45,7 +45,6 @@ jobs:
 
           sudo rm -rf redpill-load_jumkey_develop
           git clone --branch develop https://github.com/jumkey/redpill-load.git redpill-load_jumkey_develop
-          rm -rf redpill-load_jumkey_develop/config/DVA1622
 
           sudo rm -rf redpill-load_PeterSuh-Q3_master
           git clone --branch master https://github.com/PeterSuh-Q3/redpill-load.git redpill-load_PeterSuh-Q3_master
@@ -91,7 +90,7 @@ jobs:
 
           if __name__ == '__main__':
               loads = {}
-              ignore=['6.2.4-25556', '7.0-41222', '7.0-41890', '7.1-42550', '7.1.0-42550', '7.1.0-42621', '7.1.1-42951']
+              ignore=['7.0-41222', '7.0-41890', '7.1-42550', '7.1-42661', '7.1.0-42550', '7.1.0-42621', '7.1.1-42951']
 
               print('################### pocopico_develop ###################')
               loads["pocopico_develop"] = getloadlist('redpill-load_pocopico_develop', ignore)
@@ -118,7 +117,7 @@ jobs:
                       f.write(json.dumps(loads, indent=4))
 
 
-      - name: Get models, toolchain and pats lsit
+      - name: Get models and pats lsit
         shell: python
         run: |
           # -*- coding: utf-8 -*-
@@ -130,13 +129,13 @@ jobs:
           if __name__ == '__main__':
 
               # models
+              models=[]
               req = requests.get('https://kb.synology.com/en-us/DSM/tutorial/What_kind_of_CPU_does_my_NAS_have')
               req.encoding = 'utf-8'
               bs=BeautifulSoup(req.text, 'html.parser')
               p = re.compile(r"data: (.*?),$", re.MULTILINE | re.DOTALL)
               data = json.loads(p.search(bs.find('script', string=p).prettify()).group(1))
 
-              models=[]
               model='(.*?)'  # (.*?): all, FS6400: one
               p = re.compile(r"\n\t\t\t<td>{}<\/td>\n\t\t\t<td>(.*?)<\/td>\n\t\t\t<td>(.*?)<\/td>\n\t\t\t<td>(.*?)<\/td>\n\t\t\t<td>(.*?)<\/td>\n\t\t\t<td>(.*?)<\/td>\n\t\t\t<td>(.*?)<\/td>\n\t\t".format(model), re.MULTILINE | re.DOTALL)
               it = p.finditer(data["preload"]["content"])
@@ -150,34 +149,8 @@ jobs:
                   f.write(json.dumps(models, indent=4))
 
 
-              # toolchain
-              req = requests.get('https://archive.synology.cn/download/ToolChain/toolchain')
-              req.encoding = 'utf-8'
-              bs=BeautifulSoup(req.text, 'html.parser')
-              p = re.compile(r"(.*?)-(.*?)", re.MULTILINE | re.DOTALL)
-              l = bs.find_all('a', string=p)
-
-              toolchain = {}
-              for i in l:
-                  req = requests.get('https://archive.synology.cn{}'.format(i.attrs['href']))
-                  req.encoding = 'utf-8'
-                  bs=BeautifulSoup(req.text, 'html.parser')
-
-                  p = re.compile(r"^(.*?)[L|l]inux(.*?)\((.*?)\)$", re.MULTILINE | re.DOTALL)
-                  data = bs.find_all('td', string=p)
-                  for item in data:
-                      info = p.search(item.string).groups()
-                      if not i.string in toolchain.keys(): toolchain[i.string] = {}
-                      toolchain[i.string][info[2].strip().lower()] = info[1].replace('Linux', '').strip()
-                      print(info)
-              
-              print(toolchain)
-              with open(os.path.join(root, 'docs/toolchain.json'), 'w', encoding='utf-8') as f:
-                  f.write(json.dumps(toolchain, indent=4))
-
-              # patindo
+              # pats
               pats = {}
-  
               req = requests.get('https://archive.synology.cn/download/Os/DSM')
               req.encoding = 'utf-8'
               bs=BeautifulSoup(req.text, 'html.parser')
@@ -208,15 +181,105 @@ jobs:
                       if i["name"] not in pats.keys(): pats[i["name"]]={}
                       pats[i["name"]][i["dsm"]["version"]] = i["dsm"]["url"].split('?')[0]
                     
-
-              print(pats)
+              print(json.dumps(pats, indent=4))
               with open(os.path.join(root, 'docs/pats.json'), 'w', encoding='utf-8') as f:
                   f.write(json.dumps(pats, indent=4))
+
+      - name: Get kernelvers lsit
+        run: |
+          function fullversion() {
+            local out=$1
+            local arr=(${1//-/ })
+            if [ ${#arr[@]} -gt 0 ]; then
+              local vers=(${arr[0]//./ })
+              a=`[ ${#vers[@]} -gt 0 ] && echo ${vers[0]} || echo "0"`
+              b=`[ ${#vers[@]} -gt 1 ] && echo ${vers[1]} || echo "0"`
+              c=`[ ${#vers[@]} -gt 2 ] && echo ${vers[2]} || echo "0"`
+              d=`[ ${#arr[@]} -gt 1 ] && echo ${arr[1]} || echo "00000"`
+              e=`[ ${#arr[@]} -gt 2 ] && echo ${arr[2]} || echo "0"`
+              out="${a}.${b}.${c}-${d}-${e}"
+            fi
+            echo ${out}
+          }
+
+          function synoextractor() {
+            if [ $# -ge 2 ]; then
+              filename=${2}
+              [[ ! ${filename} =~ .pat$ ]] && filename="${filename}.pat"
+            else
+              filename=${1}
+              filename=${filename##*\/}
+              filename=${filename%%\?*}
+            fi
+
+            curl -#kL "$1" -o ${filename}
+
+            header="$(od -bcN2 ${filename} | head -1 | awk '{print $3}')"
+            case ${header} in
+              105)
+                echo "Uncompressed tar"
+                isencrypted="no"
+                ;;
+              213)
+                echo "Compressed tar"
+                isencrypted="no"
+                ;;
+              255)
+                echo "Encrypted"
+                isencrypted="yes"
+                ;;
+              *)
+                echo "error"
+                return 1
+                ;;
+            esac
+
+            [ -d "${filename%%\.*}" ] && rm -rf "${filename%%\.*}"
+            mkdir -p "${filename%%\.*}"
+
+            if [ "${isencrypted}" = "yes" ]; then
+              sudo $GITHUB_WORKSPACE/syno-extractor.sh "${filename}" "${filename%%\.*}"
+            else
+              tar -xf "${filename}" -C "${filename%%\.*}" >/dev/null 2>&1
+            fi
+            rm -f ${filename}
+          }
+
+          chmod +x $GITHUB_WORKSPACE/syno-extractor.sh
+
+          JSON=docs/kernelvers.json
+          [ ! -f ${JSON} ] && echo -e '{}' > ${JSON}
+          models=(`jq -r '. | keys | tostring' $GITHUB_WORKSPACE/docs/pats.json | cut -d '[' -f2 | cut -d ']' -f1 | sed 's/,/ /g' | sed 's/\"//g'`)
+          echo ${models[@]}
+          for model in ${models[@]}
+          do
+            [ `jq -r --arg model "${model}" '.[] | has($model)' $GITHUB_WORKSPACE/docs/loads.json 2>/dev/null | grep -E 'true' | wc -l` -eq 0 ] && continue 1
+            synoarch=$(jq -r --arg model "${model}" '. | map(select(.Model == $model)) | .[].PackageArch' $GITHUB_WORKSPACE/docs/models.json)
+            [ -z "${synoarch}" ] && continue 1
+            [ "false" == "`jq -r --arg arch ${synoarch} '. | has($arch)' ${JSON}`" ] && echo -e "`jq -r --arg arch ${synoarch} '.[$arch] = {}' ${JSON}`" > ${JSON}
+            vers=(`jq -r --arg model ${model} '.[$model] | keys | tostring' $GITHUB_WORKSPACE/docs/pats.json | cut -d '[' -f2 | cut -d ']' -f1 | sed 's/,/ /g' | sed 's/\"//g'`)
+
+            for ver in ${vers[@]}
+            do
+              fullver=`fullversion ${ver}`
+              fullver=${fullver%\-*}
+              [ "true" == "`jq -r --arg arch ${synoarch} --arg fullver ${fullver} '.[$arch] | has($fullver)' ${JSON}`" ] && continue 1
+              url=`jq -r --arg model ${model} --arg ver ${ver} '.[$model][$ver]' $GITHUB_WORKSPACE/docs/pats.json`
+              synoextractor ${url} DSM
+              if [ -f DSM/zImage ]; then
+                kernelver=`file "DSM/zImage" | awk '{printf $9}' | sed 's/+//g'`
+                echo -e "`jq -r --arg arch ${synoarch} --arg fullver ${fullver} --arg kernelver ${kernelver} '.[$arch][$fullver] = $kernelver' ${JSON}`" > ${JSON}
+                echo "${model} -- ${synoarch} -- ${fullver} -- ${url} -- ${kernelver}"
+              fi
+              sudo rm -rf DSM
+            done
+          done
+
 
       - name: Check and Push
         run: |
           git pull
-          status=$(git status -s | grep -E 'loads.json|models.json|toolchain.json|pats.json' | awk '{printf " %s", $2}')
+          status=$(git status -s | grep -E 'loads.json|models.json|pats.json|kernelvers.json' | awk '{printf " %s", $2}')
           if [ -n "${status}" ]; then
             git add ${status}
             git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
